// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timer.proto

package pb_timer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//end type
type TimerType int32

const (
	TimerType_ETimerTypeNone      TimerType = 0
	TimerType_ETimerTypeNew       TimerType = 1
	TimerType_ETimerTypeUpsert    TimerType = 2
	TimerType_ETimerTypeTimeout   TimerType = 11
	TimerType_ETimerEndTypeDelete TimerType = 12
	TimerType_ETimerEndTypeError  TimerType = 10000
)

var TimerType_name = map[int32]string{
	0:     "ETimerTypeNone",
	1:     "ETimerTypeNew",
	2:     "ETimerTypeUpsert",
	11:    "ETimerTypeTimeout",
	12:    "ETimerEndTypeDelete",
	10000: "ETimerEndTypeError",
}

var TimerType_value = map[string]int32{
	"ETimerTypeNone":      0,
	"ETimerTypeNew":       1,
	"ETimerTypeUpsert":    2,
	"ETimerTypeTimeout":   11,
	"ETimerEndTypeDelete": 12,
	"ETimerEndTypeError":  10000,
}

func (x TimerType) String() string {
	return proto.EnumName(TimerType_name, int32(x))
}

func (TimerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{0}
}

//timer
type TimerInfo struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 TimerType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.timer.TimerType" json:"type,omitempty"`
	DelaySeconds         int64     `protobuf:"varint,3,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	Topic                string    `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	SubTopic             string    `protobuf:"bytes,5,opt,name=sub_topic,json=subTopic,proto3" json:"sub_topic,omitempty"`
	TopicMsg             int32     `protobuf:"varint,6,opt,name=topic_msg,json=topicMsg,proto3" json:"topic_msg,omitempty"`
	Data                 string    `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	StartTime            int64     `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64     `protobuf:"varint,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	EventType            string    `protobuf:"bytes,10,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	NotReplaceData       bool      `protobuf:"varint,11,opt,name=not_replace_data,json=notReplaceData,proto3" json:"not_replace_data,omitempty"`
	NotNotify            bool      `protobuf:"varint,20,opt,name=not_notify,json=notNotify,proto3" json:"not_notify,omitempty"`
	Metadata             string    `protobuf:"bytes,21,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TimerInfo) Reset()         { *m = TimerInfo{} }
func (m *TimerInfo) String() string { return proto.CompactTextString(m) }
func (*TimerInfo) ProtoMessage()    {}
func (*TimerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{0}
}

func (m *TimerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerInfo.Unmarshal(m, b)
}
func (m *TimerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerInfo.Marshal(b, m, deterministic)
}
func (m *TimerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerInfo.Merge(m, src)
}
func (m *TimerInfo) XXX_Size() int {
	return xxx_messageInfo_TimerInfo.Size(m)
}
func (m *TimerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TimerInfo proto.InternalMessageInfo

func (m *TimerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TimerInfo) GetType() TimerType {
	if m != nil {
		return m.Type
	}
	return TimerType_ETimerTypeNone
}

func (m *TimerInfo) GetDelaySeconds() int64 {
	if m != nil {
		return m.DelaySeconds
	}
	return 0
}

func (m *TimerInfo) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *TimerInfo) GetSubTopic() string {
	if m != nil {
		return m.SubTopic
	}
	return ""
}

func (m *TimerInfo) GetTopicMsg() int32 {
	if m != nil {
		return m.TopicMsg
	}
	return 0
}

func (m *TimerInfo) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TimerInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TimerInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *TimerInfo) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *TimerInfo) GetNotReplaceData() bool {
	if m != nil {
		return m.NotReplaceData
	}
	return false
}

func (m *TimerInfo) GetNotNotify() bool {
	if m != nil {
		return m.NotNotify
	}
	return false
}

func (m *TimerInfo) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

type WatchReq struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Stop                 bool     `protobuf:"varint,2,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchReq) Reset()         { *m = WatchReq{} }
func (m *WatchReq) String() string { return proto.CompactTextString(m) }
func (*WatchReq) ProtoMessage()    {}
func (*WatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{1}
}

func (m *WatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchReq.Unmarshal(m, b)
}
func (m *WatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchReq.Marshal(b, m, deterministic)
}
func (m *WatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchReq.Merge(m, src)
}
func (m *WatchReq) XXX_Size() int {
	return xxx_messageInfo_WatchReq.Size(m)
}
func (m *WatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_WatchReq proto.InternalMessageInfo

func (m *WatchReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *WatchReq) GetStop() bool {
	if m != nil {
		return m.Stop
	}
	return false
}

type ErrInfo struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrInfo) Reset()         { *m = ErrInfo{} }
func (m *ErrInfo) String() string { return proto.CompactTextString(m) }
func (*ErrInfo) ProtoMessage()    {}
func (*ErrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{2}
}

func (m *ErrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrInfo.Unmarshal(m, b)
}
func (m *ErrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrInfo.Marshal(b, m, deterministic)
}
func (m *ErrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrInfo.Merge(m, src)
}
func (m *ErrInfo) XXX_Size() int {
	return xxx_messageInfo_ErrInfo.Size(m)
}
func (m *ErrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ErrInfo proto.InternalMessageInfo

func (m *ErrInfo) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ErrInfo) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

//req
type TimerReq struct {
	TimerInfo            *TimerInfo `protobuf:"bytes,1,opt,name=timer_info,json=timerInfo,proto3" json:"timer_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TimerReq) Reset()         { *m = TimerReq{} }
func (m *TimerReq) String() string { return proto.CompactTextString(m) }
func (*TimerReq) ProtoMessage()    {}
func (*TimerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{3}
}

func (m *TimerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerReq.Unmarshal(m, b)
}
func (m *TimerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerReq.Marshal(b, m, deterministic)
}
func (m *TimerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerReq.Merge(m, src)
}
func (m *TimerReq) XXX_Size() int {
	return xxx_messageInfo_TimerReq.Size(m)
}
func (m *TimerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerReq.DiscardUnknown(m)
}

var xxx_messageInfo_TimerReq proto.InternalMessageInfo

func (m *TimerReq) GetTimerInfo() *TimerInfo {
	if m != nil {
		return m.TimerInfo
	}
	return nil
}

//ack
type TimerAck struct {
	ErrInfo              *ErrInfo   `protobuf:"bytes,1,opt,name=err_info,json=errInfo,proto3" json:"err_info,omitempty"`
	TimerInfo            *TimerInfo `protobuf:"bytes,2,opt,name=timer_info,json=timerInfo,proto3" json:"timer_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TimerAck) Reset()         { *m = TimerAck{} }
func (m *TimerAck) String() string { return proto.CompactTextString(m) }
func (*TimerAck) ProtoMessage()    {}
func (*TimerAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{4}
}

func (m *TimerAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerAck.Unmarshal(m, b)
}
func (m *TimerAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerAck.Marshal(b, m, deterministic)
}
func (m *TimerAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerAck.Merge(m, src)
}
func (m *TimerAck) XXX_Size() int {
	return xxx_messageInfo_TimerAck.Size(m)
}
func (m *TimerAck) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerAck.DiscardUnknown(m)
}

var xxx_messageInfo_TimerAck proto.InternalMessageInfo

func (m *TimerAck) GetErrInfo() *ErrInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *TimerAck) GetTimerInfo() *TimerInfo {
	if m != nil {
		return m.TimerInfo
	}
	return nil
}

//
type GetTimerReq struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	SubTopic             string   `protobuf:"bytes,2,opt,name=sub_topic,json=subTopic,proto3" json:"sub_topic,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTimerReq) Reset()         { *m = GetTimerReq{} }
func (m *GetTimerReq) String() string { return proto.CompactTextString(m) }
func (*GetTimerReq) ProtoMessage()    {}
func (*GetTimerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{5}
}

func (m *GetTimerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTimerReq.Unmarshal(m, b)
}
func (m *GetTimerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTimerReq.Marshal(b, m, deterministic)
}
func (m *GetTimerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTimerReq.Merge(m, src)
}
func (m *GetTimerReq) XXX_Size() int {
	return xxx_messageInfo_GetTimerReq.Size(m)
}
func (m *GetTimerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTimerReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTimerReq proto.InternalMessageInfo

func (m *GetTimerReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GetTimerReq) GetSubTopic() string {
	if m != nil {
		return m.SubTopic
	}
	return ""
}

func (m *GetTimerReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TimerListReq struct {
	TimerList            []*GetTimerReq `protobuf:"bytes,1,rep,name=timer_list,json=timerList,proto3" json:"timer_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TimerListReq) Reset()         { *m = TimerListReq{} }
func (m *TimerListReq) String() string { return proto.CompactTextString(m) }
func (*TimerListReq) ProtoMessage()    {}
func (*TimerListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{6}
}

func (m *TimerListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerListReq.Unmarshal(m, b)
}
func (m *TimerListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerListReq.Marshal(b, m, deterministic)
}
func (m *TimerListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerListReq.Merge(m, src)
}
func (m *TimerListReq) XXX_Size() int {
	return xxx_messageInfo_TimerListReq.Size(m)
}
func (m *TimerListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerListReq.DiscardUnknown(m)
}

var xxx_messageInfo_TimerListReq proto.InternalMessageInfo

func (m *TimerListReq) GetTimerList() []*GetTimerReq {
	if m != nil {
		return m.TimerList
	}
	return nil
}

//
//message TimerListReq {
//    repeated string ids = 1;
//}
type TimerListAck struct {
	ErrInfo              *ErrInfo     `protobuf:"bytes,1,opt,name=err_info,json=errInfo,proto3" json:"err_info,omitempty"`
	TimerList            []*TimerInfo `protobuf:"bytes,2,rep,name=timer_list,json=timerList,proto3" json:"timer_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TimerListAck) Reset()         { *m = TimerListAck{} }
func (m *TimerListAck) String() string { return proto.CompactTextString(m) }
func (*TimerListAck) ProtoMessage()    {}
func (*TimerListAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad0307ee16b652d2, []int{7}
}

func (m *TimerListAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimerListAck.Unmarshal(m, b)
}
func (m *TimerListAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimerListAck.Marshal(b, m, deterministic)
}
func (m *TimerListAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimerListAck.Merge(m, src)
}
func (m *TimerListAck) XXX_Size() int {
	return xxx_messageInfo_TimerListAck.Size(m)
}
func (m *TimerListAck) XXX_DiscardUnknown() {
	xxx_messageInfo_TimerListAck.DiscardUnknown(m)
}

var xxx_messageInfo_TimerListAck proto.InternalMessageInfo

func (m *TimerListAck) GetErrInfo() *ErrInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *TimerListAck) GetTimerList() []*TimerInfo {
	if m != nil {
		return m.TimerList
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.timer.TimerType", TimerType_name, TimerType_value)
	proto.RegisterType((*TimerInfo)(nil), "pb.timer.TimerInfo")
	proto.RegisterType((*WatchReq)(nil), "pb.timer.WatchReq")
	proto.RegisterType((*ErrInfo)(nil), "pb.timer.ErrInfo")
	proto.RegisterType((*TimerReq)(nil), "pb.timer.TimerReq")
	proto.RegisterType((*TimerAck)(nil), "pb.timer.TimerAck")
	proto.RegisterType((*GetTimerReq)(nil), "pb.timer.GetTimerReq")
	proto.RegisterType((*TimerListReq)(nil), "pb.timer.TimerListReq")
	proto.RegisterType((*TimerListAck)(nil), "pb.timer.TimerListAck")
}

func init() { proto.RegisterFile("timer.proto", fileDescriptor_ad0307ee16b652d2) }

var fileDescriptor_ad0307ee16b652d2 = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x4f, 0xd4, 0x40,
	0x14, 0xa5, 0xdd, 0xaf, 0xf6, 0x2e, 0x6c, 0xca, 0x05, 0xa4, 0xae, 0x21, 0xd9, 0xd4, 0x07, 0x1b,
	0x63, 0x36, 0x64, 0xc5, 0xe8, 0x0b, 0x26, 0x28, 0x1b, 0x63, 0x22, 0xc4, 0x14, 0x8c, 0x8f, 0x4d,
	0xb7, 0x1d, 0xb0, 0x61, 0xe9, 0x94, 0x99, 0x41, 0xb3, 0xbf, 0xc1, 0x17, 0xfd, 0x13, 0xfe, 0x4e,
	0x33, 0x77, 0x5a, 0x76, 0x59, 0x89, 0x91, 0xf8, 0x36, 0x73, 0xce, 0x9c, 0x7b, 0xce, 0xdc, 0x3b,
	0x2d, 0x74, 0x55, 0x7e, 0xc9, 0xc4, 0xb0, 0x14, 0x5c, 0x71, 0x74, 0xca, 0xc9, 0x90, 0xf6, 0xc1,
	0xf7, 0x06, 0xb8, 0xa7, 0x7a, 0xf5, 0xbe, 0x38, 0xe3, 0xd8, 0x03, 0x3b, 0xcf, 0x7c, 0x6b, 0x60,
	0x85, 0x6e, 0x64, 0xe7, 0x19, 0x3e, 0x81, 0xa6, 0x9a, 0x95, 0xcc, 0xb7, 0x07, 0x56, 0xd8, 0x1b,
	0x6d, 0x0c, 0x6b, 0xd9, 0x90, 0x24, 0xa7, 0xb3, 0x92, 0x45, 0x74, 0x00, 0x1f, 0xc3, 0x5a, 0xc6,
	0xa6, 0xc9, 0x2c, 0x96, 0x2c, 0xe5, 0x45, 0x26, 0xfd, 0xc6, 0xc0, 0x0a, 0x1b, 0xd1, 0x2a, 0x81,
	0x27, 0x06, 0xc3, 0x4d, 0x68, 0x29, 0x5e, 0xe6, 0xa9, 0xdf, 0x24, 0x03, 0xb3, 0xc1, 0x47, 0xe0,
	0xca, 0xeb, 0x49, 0x6c, 0x98, 0x16, 0x31, 0x8e, 0xbc, 0x9e, 0x9c, 0xd6, 0x24, 0x11, 0xf1, 0xa5,
	0x3c, 0xf7, 0xdb, 0x03, 0x2b, 0x6c, 0x45, 0x0e, 0x01, 0x47, 0xf2, 0x1c, 0x11, 0x9a, 0x59, 0xa2,
	0x12, 0xbf, 0x43, 0x22, 0x5a, 0xe3, 0x0e, 0x80, 0x54, 0x89, 0x50, 0xb1, 0xce, 0xe9, 0x3b, 0x94,
	0xc2, 0x25, 0x44, 0x47, 0xc6, 0x87, 0xe0, 0xb0, 0x22, 0x33, 0xa4, 0x4b, 0x64, 0x87, 0x15, 0x19,
	0x51, 0x3b, 0x00, 0xec, 0x2b, 0x2b, 0x54, 0x4c, 0x37, 0x06, 0xaa, 0xe9, 0x12, 0xa2, 0xef, 0x89,
	0x21, 0x78, 0x05, 0x57, 0xb1, 0x60, 0xe5, 0x34, 0x49, 0x59, 0x4c, 0xc6, 0xdd, 0x81, 0x15, 0x3a,
	0x51, 0xaf, 0xe0, 0x2a, 0x32, 0xf0, 0x61, 0x15, 0x41, 0x9f, 0x2c, 0xb8, 0xca, 0xcf, 0x66, 0xfe,
	0x26, 0x9d, 0x71, 0x0b, 0xae, 0x8e, 0x09, 0xc0, 0x3e, 0x38, 0x97, 0x4c, 0x25, 0x54, 0x60, 0xcb,
	0x5c, 0xb7, 0xde, 0x07, 0x7b, 0xe0, 0x7c, 0x4e, 0x54, 0xfa, 0x25, 0x62, 0x57, 0xf3, 0x6e, 0x59,
	0x8b, 0xdd, 0x42, 0x68, 0x4a, 0xc5, 0x4b, 0x9a, 0x88, 0x13, 0xd1, 0x3a, 0xd8, 0x87, 0xce, 0x58,
	0x98, 0x01, 0xea, 0xfb, 0x09, 0x11, 0xa7, 0x3c, 0x63, 0xa4, 0x6b, 0x45, 0x1d, 0x26, 0xc4, 0x5b,
	0x9e, 0x31, 0xdc, 0x06, 0xbd, 0xa4, 0x46, 0xda, 0x54, 0xb1, 0xcd, 0x84, 0x38, 0x92, 0xe7, 0xc1,
	0x6b, 0x70, 0x68, 0x9c, 0xda, 0x74, 0x04, 0x40, 0x03, 0x8e, 0xf3, 0xe2, 0x8c, 0x53, 0x85, 0xee,
	0x1f, 0x63, 0xd7, 0x46, 0x91, 0xab, 0xea, 0x65, 0x30, 0xad, 0xf4, 0x07, 0xe9, 0x05, 0x3e, 0x33,
	0xfe, 0x0b, 0xea, 0xf5, 0xb9, 0xba, 0x0a, 0x49, 0x91, 0x28, 0xed, 0x6d, 0x37, 0xfb, 0x9f, 0xdc,
	0x3e, 0x42, 0xf7, 0x1d, 0x53, 0x37, 0x81, 0xef, 0xee, 0xd2, 0xad, 0x37, 0x65, 0x2f, 0xbd, 0x29,
	0xf3, 0xc8, 0x1b, 0xf5, 0x23, 0x0f, 0x0e, 0x61, 0x95, 0xca, 0x7d, 0xc8, 0xa5, 0xd2, 0x25, 0xf7,
	0xea, 0x54, 0xd3, 0x5c, 0x2a, 0xdf, 0x1a, 0x34, 0xc2, 0xee, 0x68, 0x6b, 0x9e, 0x6a, 0xc1, 0xbd,
	0xca, 0xa5, 0x85, 0x41, 0xb9, 0x50, 0xe5, 0x3f, 0x3a, 0x41, 0x9e, 0x36, 0x79, 0xfe, 0xa5, 0x13,
	0xda, 0xe4, 0xe9, 0x4f, 0xab, 0xfa, 0x74, 0xe9, 0x7d, 0x22, 0xf4, 0xc6, 0x37, 0xbb, 0x63, 0x5e,
	0x30, 0x6f, 0x05, 0xd7, 0x61, 0x6d, 0x01, 0x63, 0xdf, 0x3c, 0x0b, 0x37, 0xc1, 0x9b, 0x43, 0x9f,
	0x4a, 0xc9, 0x84, 0xf2, 0x6c, 0xdc, 0x82, 0xf5, 0x39, 0xaa, 0x17, 0xfc, 0x5a, 0x79, 0x5d, 0xdc,
	0x86, 0x0d, 0x03, 0x8f, 0x8b, 0x4c, 0x33, 0x87, 0x6c, 0xca, 0x14, 0xf3, 0x56, 0x71, 0x1b, 0xf0,
	0x16, 0x31, 0x16, 0x82, 0x0b, 0xef, 0xc7, 0xf1, 0xe8, 0x97, 0x0d, 0x2d, 0x22, 0x70, 0x0f, 0x9c,
	0x93, 0xaa, 0x53, 0x88, 0x4b, 0x37, 0x89, 0xd8, 0x55, 0x7f, 0x19, 0x3b, 0x48, 0x2f, 0x82, 0x15,
	0xdc, 0x07, 0xb7, 0xee, 0xaf, 0xc4, 0x07, 0x4b, 0x47, 0xaa, 0x01, 0xf5, 0xef, 0xc2, 0x8d, 0xfc,
	0x25, 0x74, 0x4d, 0xc6, 0xfb, 0xfa, 0xbe, 0x80, 0x76, 0xf5, 0x79, 0x2e, 0xf0, 0xf5, 0xa7, 0xd8,
	0xbf, 0x6b, 0x12, 0xc1, 0xca, 0xae, 0x85, 0xaf, 0xa0, 0x63, 0x64, 0x6f, 0xee, 0xa1, 0x0b, 0xad,
	0x5d, 0x6b, 0xd2, 0xa6, 0x1f, 0xf1, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x57, 0x04,
	0x4e, 0x97, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TimerClient is the client API for Timer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimerClient interface {
	SetTimer(ctx context.Context, in *TimerReq, opts ...grpc.CallOption) (*TimerAck, error)
	GetTimers(ctx context.Context, in *TimerListReq, opts ...grpc.CallOption) (*TimerListAck, error)
	DeleteTimer(ctx context.Context, in *TimerReq, opts ...grpc.CallOption) (*TimerAck, error)
	Notify(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (Timer_NotifyClient, error)
	NotifyB(ctx context.Context, opts ...grpc.CallOption) (Timer_NotifyBClient, error)
}

type timerClient struct {
	cc *grpc.ClientConn
}

func NewTimerClient(cc *grpc.ClientConn) TimerClient {
	return &timerClient{cc}
}

func (c *timerClient) SetTimer(ctx context.Context, in *TimerReq, opts ...grpc.CallOption) (*TimerAck, error) {
	out := new(TimerAck)
	err := c.cc.Invoke(ctx, "/pb.timer.Timer/SetTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerClient) GetTimers(ctx context.Context, in *TimerListReq, opts ...grpc.CallOption) (*TimerListAck, error) {
	out := new(TimerListAck)
	err := c.cc.Invoke(ctx, "/pb.timer.Timer/GetTimers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerClient) DeleteTimer(ctx context.Context, in *TimerReq, opts ...grpc.CallOption) (*TimerAck, error) {
	out := new(TimerAck)
	err := c.cc.Invoke(ctx, "/pb.timer.Timer/DeleteTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timerClient) Notify(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (Timer_NotifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Timer_serviceDesc.Streams[0], "/pb.timer.Timer/Notify", opts...)
	if err != nil {
		return nil, err
	}
	x := &timerNotifyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Timer_NotifyClient interface {
	Recv() (*TimerInfo, error)
	grpc.ClientStream
}

type timerNotifyClient struct {
	grpc.ClientStream
}

func (x *timerNotifyClient) Recv() (*TimerInfo, error) {
	m := new(TimerInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *timerClient) NotifyB(ctx context.Context, opts ...grpc.CallOption) (Timer_NotifyBClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Timer_serviceDesc.Streams[1], "/pb.timer.Timer/NotifyB", opts...)
	if err != nil {
		return nil, err
	}
	x := &timerNotifyBClient{stream}
	return x, nil
}

type Timer_NotifyBClient interface {
	Send(*WatchReq) error
	Recv() (*TimerInfo, error)
	grpc.ClientStream
}

type timerNotifyBClient struct {
	grpc.ClientStream
}

func (x *timerNotifyBClient) Send(m *WatchReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *timerNotifyBClient) Recv() (*TimerInfo, error) {
	m := new(TimerInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TimerServer is the server API for Timer service.
type TimerServer interface {
	SetTimer(context.Context, *TimerReq) (*TimerAck, error)
	GetTimers(context.Context, *TimerListReq) (*TimerListAck, error)
	DeleteTimer(context.Context, *TimerReq) (*TimerAck, error)
	Notify(*WatchReq, Timer_NotifyServer) error
	NotifyB(Timer_NotifyBServer) error
}

func RegisterTimerServer(s *grpc.Server, srv TimerServer) {
	s.RegisterService(&_Timer_serviceDesc, srv)
}

func _Timer_SetTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).SetTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.timer.Timer/SetTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).SetTimer(ctx, req.(*TimerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timer_GetTimers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimerListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).GetTimers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.timer.Timer/GetTimers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).GetTimers(ctx, req.(*TimerListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timer_DeleteTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimerServer).DeleteTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.timer.Timer/DeleteTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimerServer).DeleteTimer(ctx, req.(*TimerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Timer_Notify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimerServer).Notify(m, &timerNotifyServer{stream})
}

type Timer_NotifyServer interface {
	Send(*TimerInfo) error
	grpc.ServerStream
}

type timerNotifyServer struct {
	grpc.ServerStream
}

func (x *timerNotifyServer) Send(m *TimerInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _Timer_NotifyB_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TimerServer).NotifyB(&timerNotifyBServer{stream})
}

type Timer_NotifyBServer interface {
	Send(*TimerInfo) error
	Recv() (*WatchReq, error)
	grpc.ServerStream
}

type timerNotifyBServer struct {
	grpc.ServerStream
}

func (x *timerNotifyBServer) Send(m *TimerInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *timerNotifyBServer) Recv() (*WatchReq, error) {
	m := new(WatchReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Timer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.timer.Timer",
	HandlerType: (*TimerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTimer",
			Handler:    _Timer_SetTimer_Handler,
		},
		{
			MethodName: "GetTimers",
			Handler:    _Timer_GetTimers_Handler,
		},
		{
			MethodName: "DeleteTimer",
			Handler:    _Timer_DeleteTimer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Notify",
			Handler:       _Timer_Notify_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NotifyB",
			Handler:       _Timer_NotifyB_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "timer.proto",
}
