# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# 全局语言，例如将侧边的“home”改成“主页”等，可选项在_data/locales/下
lang: zh-CN
# 时区
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: L # the main title

tagline: 随便写写 # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  A personal blog for recording pieces of thoughts.

# 站点域名，注意结尾不包括 '/'
url: "https://auroraol.github.io"
# github名，改成自己的github名字
github:
  username: Auroraol # change to your GitHub username
# twitter名，改成自己的twitter名字
# twitter:
#   username: twitter_username # change to your Twitter username

### 自己的社交帐号信息，在页脚中显示为文章的默认作者和版权所有者。
social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: lfj
  # email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/Auroraol
  # Uncomment below to add more social links
  # - https://www.facebook.com/username
  # - https://www.linkedin.com/in/username

# 站点验证设置，默认为空
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# 网页分析设置，默认为空
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# 页面查看次数设置，现在只支持'goatcounter'，默认为空
pageviews:
  provider: # now only supports 'goatcounter'

# 首选颜色方案设置。留空将默认遵循系统首选颜色，并且在侧边栏的左下角会有一个开关来在深色和浅色之间切换主题
# theme_mode: [dark | light] # [light | dark]

# 媒体资源的 CDN 地址。
img_cdn: https://testingcf.jsdelivr.net/gh/Auroraol/auroraol.github.io

# 社交预览图像，没什么用
social_preview_image: # string, local or CORS resources

# 侧边栏头像，支持本地或 CORS 资源
avatar: "/assets/img/avatar.jpeg"

# 社交预览图像，没什么用
social_preview_image: # string, local or CORS resources

# 博客中目录的全局开关。true | false
toc: true

# 评论相关，默认禁用。
comments:
  # 帖子评论系统的全局开关。将其留空表示禁用。
  provider: giscus # [disqus | utterances | giscus]
  # The provider options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: "auroraol/auroraol.github.io" # <gh-username>/<repo>
    repo_id: "R_kgDOQNpBGw"
    category: "Comments"
    category_id: "DIC_kwDOQNpBG84CxWyu"
    mapping: "title" # optional, default to 'pathname'
    strict: "0" # optional, default to '0'
    input_position: "bottom" # optional, default to 'bottom'
    lang: zh-CN # optional, default to the value of `site.lang`
    reactions_enabled: "1" # optional, default to the value of `1`

# 自托管静态资产，没什么用。留空禁止
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development | production]
#PWA有关
pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA
# 分页
paginate: 10

# The base URL of your site
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------
# 不建议修改以下选项
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # permalink: /posts/:title/ 默认posts/槽位.md
      # 之前是通过日期作子目录的方式, 注释掉
      # permalink   : date
      # 添加category内容 
      # _posts\test\demo\槽位.md
      permalink: /:categories/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
