syntax = "proto3";

package pb.timer;


// The rpc service definition.
service Timer {
  rpc SetTimer (TimerReq) returns (TimerAck) {}
  rpc GetTimers (TimerListReq) returns (TimerListAck) {}
  rpc DeleteTimer (TimerReq) returns (TimerAck) {}
  rpc Notify (WatchReq) returns (stream TimerInfo) {}
  rpc NotifyB (stream WatchReq) returns (stream TimerInfo) {}
}

//end type
enum TimerType {
    ETimerTypeNone = 0;
    ETimerTypeNew = 1;
    ETimerTypeUpsert = 2;
    ETimerTypeTimeout = 11;
    ETimerEndTypeDelete  = 12;
    ETimerEndTypeError   = 10000;
}

//timer
message TimerInfo
{
    string id           = 1; //如果没有传ID则自动生成一个（可选）
    TimerType type      = 2; //timer当前类型（必填）
    int64 delay_seconds = 3; //延迟时间（必填）
    string topic        = 4; //服务类型
    string sub_topic    = 5; //
    int32 topic_msg     = 6; //notify主题下的消息编号(可选)
    string data         = 7; //自定义数据（可选）
    int64 start_time    = 8; //timer开始时间 [server生成,注意：ETimerTypeUpsert时会被重置为server当前时间]
    int64 end_time      = 9; //timer结束时间 [server生成]
    string event_type   = 10;
    bool not_replace_data = 11; // 不更新数据
    bool not_notify     = 20; //不发送通知[默认false要发送]
    string metadata     = 21; //metadata信息[上下文信息，内部使用]
}

message WatchReq {
  string topic = 1;
  bool stop = 2;
}


message ErrInfo
{
    int32  err_code = 1;
    string err_msg  = 2;
}

//req
message TimerReq {
    TimerInfo timer_info = 1;
}
//ack
message TimerAck {
    ErrInfo  err_info  = 1;
    TimerInfo timer_info = 2;
}

//
message GetTimerReq {
    string topic = 1;
    string sub_topic = 2;
    string id = 3;
}

message TimerListReq {
    repeated GetTimerReq timer_list = 1;
}

//
//message TimerListReq {
//    repeated string ids = 1;
//}
message TimerListAck {
    ErrInfo  err_info  = 1;
    repeated TimerInfo timer_list = 2;
}

