name: HTML Proofer

on:
  push:
  pull_request:

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Ensure test group dependencies are installed
        run: |
          bundle config unset without
          bundle install --jobs 4 --retry 3
      - name: Build site
        run: bundle exec jekyll build
      - name: Run HTML Proofer
        run: |
          bundle exec htmlproofer _site \
            --allow-hash-href \
            --empty-alt-ignore \
            --only-4xx \
            --url-ignore "/fonts\.googleapis\.com/" \
            --url-ignore "/fonts\.gstatic\.com/" \
            --url-ignore "/www\.toptal\.com/"

